#!/usr/bin/env node
/**
 * relate.mjs — drive the relation migration off data/_relation_schema.json.
 *
 * The point of this script is that the decision procedure and the audit are
 * both GENERATED from one table. The first draft of the proposal had a
 * hand-written procedure that silently disagreed with its own tables in four
 * places, one of which would have mis-filed all 224 utility edges. A procedure
 * that is generated cannot drift.
 *
 * Usage:
 *   node scripts/relate.mjs plan                 tally every edge -> disposition
 *   node scripts/relate.mjs procedure            emit the agent decision procedure
 *   node scripts/relate.mjs work --file X.json   work list for one fragment
 *   node scripts/relate.mjs gold [--n 80]        the calibration gold set
 *   node scripts/relate.mjs verify-inputs        the 628 inputs-derived edges
 *   node scripts/relate.mjs audit                tree-wide rule check
 *
 * Reads public/tree.json, so run `node scripts/build.mjs` first. That file is
 * stale by design mid-phase (HANDOFF, patchtest); every command prints the
 * build timestamp it saw so a stale run is obvious.
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA = JSON.parse(await readFile(path.join(ROOT, 'data/_relation_schema.json'), 'utf8'));
const { meta, nodes: N } = JSON.parse(await readFile(path.join(ROOT, 'public/tree.json'), 'utf8'));
const ids = Object.keys(N);
const K = (id) => N[id]?.kind ?? '?';
const nameOf = (id) => N[id]?.name ?? id;
const short = (id) => N[id]?.name?.slice(0, 54) ?? id;

const argv = process.argv.slice(2);
const cmd = argv[0] ?? 'plan';
/* `--x` alone is true; `--x v` is v unless v starts with `--`. Getting this
 * wrong is how `--write` silently did nothing for two runs. */
const flag = (k, d = null) => {
  const i = argv.indexOf('--' + k);
  if (i < 0) return d;
  const next = argv[i + 1];
  if (next === undefined || next.startsWith('--')) return true;
  return next;
};

/* ------------------------------------------------------------------------ */
/* the schema table -> a lookup                                             */

const RELATIONS = SCHEMA.relations;
/* Schema keys read `material->material` for readability; pair keys are built as
 * `material>material`. Normalise here, once, so the two can never disagree. */
const JUDGEMENTS = Object.fromEntries(
  Object.entries(SCHEMA.judgement_questions)
    .filter(([k]) => !k.startsWith('$'))
    .map(([k, v]) => [k.replace('->', '>'), v]),
);

/** Per-edge dispositions decided by measurement, not by judgement.
 *  Generated by `relate.mjs emit-fixes` and reviewed before use. */
let FIXES = { delete: [], reverse: {} };
try {
  FIXES = JSON.parse(await readFile(path.join(ROOT, 'data/_relation_fixes.json'), 'utf8'));
} catch { /* not generated yet */ }
const DELETE_SET = new Set((FIXES.delete ?? []).map((d) => `${d.from}>${d.to}`));
const REVERSE_MAP = new Map(Object.entries(FIXES.reverse ?? {}).map(([k, v]) => [k.replace(/\|/g, '>'), v]));
const REASSIGN_SET = new Map((FIXES.reassign ?? []).map((d) => [`${d.from}>${d.to}`, d.to_relation]));
const REVIEW_SET = new Set((FIXES.review ?? []).map((d) => `${d.from}>${d.to}`));
const FIX_WHY = new Map([...FIXES.delete ?? [], ...FIXES.reassign ?? []].map((d) => [`${d.from}>${d.to}`, d.why]));

/* Hub rules fix the relation BY TARGET NODE, overriding the kind-pair table.
 * Checked before the judgement questions: the 241 edges into the five utility
 * deliveries are not decisions, and spending an agent's attention on them would
 * be the single largest waste in the judgement pass. */
const HUB_RULES = Object.fromEntries(
  /* `$comment` and `_fanin` are documentation keys, not node ids. Filtering only
   * on `_` let `$comment` through, which made the count read 6 instead of 5 and
   * would have made every audit run check a non-existent node. Phase 0: also
   * exclude schema meta keys (applies_to_sources, scope notes); only node ids
   * (containing a dot) are hub targets. */
  Object.entries(SCHEMA.hub_rules ?? {}).filter(([k]) => !k.startsWith('_') && !k.startsWith('$') && k.includes('.')),
);

/** kind-pair -> { disposition, detail }. Judgement questions are consulted
 *  FIRST, because a question is a deliberate override of the mechanical
 *  default; then relations, in schema order. */
function classify(e) {
  if (K(e.parent) === 'note') {
    return { disposition: 'NO-HOME', why: 'edges do not leave a note; the node is mis-typed or is an index (RELATIONS.md §5)' };
  }
  const fixKey = `${e.parent}>${e.child}`;
  if (DELETE_SET.has(fixKey)) return { disposition: 'DELETE', why: FIX_WHY.get(fixKey) ?? 'RELATIONS.md §7' };
  if (REASSIGN_SET.has(fixKey)) {
    const to = REASSIGN_SET.get(fixKey);
    return { disposition: to, why: FIX_WHY.get(fixKey) ?? `reassigned to ${to}` };
  }
  if (REVIEW_SET.has(fixKey)) return { disposition: 'REVIEW', why: 'NOT DECIDED — see data/_relation_fixes.json' };
  if (REVERSE_MAP.has(fixKey)) {
    const to = REVERSE_MAP.get(fixKey);
    return { disposition: 'REVERSE', to, why: `stored backwards; becomes ${to}` };
  }
  if (K(e.child) === 'note') return { disposition: 'about', why: RELATIONS.about.test };

  const hub = HUB_RULES[e.child];
  if (hub && hub.relation) {
    // Phase 0 (Wave 3 §5-8/31/36): hub_rules fires only for storable sources.
    // consumes stores process/tool/facility->material only; other sources fall
    // through to judgement/mechanical so answer_must_be_storable never fails.
    // Also never fires on a `children` containment edge (delivery infrastructure).
    const allowed = SCHEMA.hub_rules?.applies_to_sources ?? ["process", "tool", "facility"];
    const srcKind = K(e.parent);
    if (allowed.includes(srcKind) && e.was !== "children") return { disposition: hub.relation, why: `hub rule: ${hub.why}` };
    // else fall through to judgement below
  }

  const j = JUDGEMENTS[e.pair];
  if (j) return { disposition: 'JUDGE', q: e.pair, rel: j.decide.split('|').map((s) => s.trim()), why: j.test, note: j.note };

  const [a, b] = e.pair.split('>');
  for (const [name, r] of Object.entries(RELATIONS)) {
    if (r.derived_from) continue;              // derived, never stored
    if (!r.stored?.length) continue;
    if (r.stored.includes(`${a}->${b}`) || r.stored.includes(`*->${b}`)) {
      return { disposition: name, why: r.test };
    }
  }
  return { disposition: 'UNMAPPED', why: `no relation stores ${a} -> ${b}, and it is not a declared judgement question` };
}

/** Post-classification assertions from `narrow_kinds`. Never a router —
 *  routing with these mis-bucketed all 126 `*->part` edges on the first run. */
function assertNarrowKinds(e, c) {
  const nk = SCHEMA.narrow_kinds;
  if (c.disposition === 'consumes' && K(e.child) === 'part') {
    return { ...c, disposition: 'ASSERT-FAIL', why: 'consumes may not target a part (narrow_kinds.consumes_part)' };
  }
  if (c.disposition === 'produces' && !nk.produces_target.includes(K(e.child))) {
    return { ...c, disposition: 'ASSERT-FAIL', why: `produces target must be one of ${nk.produces_target}` };
  }
  if (c.disposition === 'uses' && K(e.child) !== 'tool' && K(e.child) !== 'process') {
    return { ...c, disposition: 'ASSERT-FAIL', why: 'uses target must be a tool' };
  }
  return c;
}

/* ------------------------------------------------------------------------ */

function allEdges() {
  const out = [];
  for (const rel of ['children', 'from']) {
    for (const id of ids) {
      for (const t of (rel === 'children' ? (N[id].children ?? []) : (N[id].from ?? []))) {
        if (!N[t]) continue;
        out.push({ parent: id, child: t, was: rel, pair: `${K(id)}>${K(t)}` });
      }
    }
  }
  return out;
}

const E = allEdges();

/* ---------------------------------------------------------------- commands */

function classifyAll() {
  return E.map((e) => {
    const c = assertNarrowKinds(e, classify(e));
    return { ...e, ...c };
  });
}

const ALL = classifyAll();

function cmdPlan() {
  const tally = new Map();
  for (const e of ALL) {
    const key = e.disposition === 'JUDGE' ? `JUDGE ${e.q}` : e.disposition;
    if (!tally.has(key)) tally.set(key, { n: 0, pairs: new Map() });
    const t = tally.get(key);
    t.n++;
    t.pairs.set(e.pair, (t.pairs.get(e.pair) ?? 0) + 1);
  }
  const grab = (pfx) => [...tally].filter(([k]) => k.startsWith(pfx));
  const sum = (list) => list.reduce((s, [, t]) => s + t.n, 0);
  const judgeN = sum(grab('JUDGE'));
  const unmappedN = tally.get('UNMAPPED')?.n ?? 0;
  const assertN = tally.get('ASSERT-FAIL')?.n ?? 0;

  console.log(`\n  build:    ${meta.generated}`);
  console.log(`  nodes:    ${ids.length}   edges: ${E.length}\n`);

  console.log(`  MECHANICAL — decided by the schema table, no judgement needed`);
  for (const [k, t] of [...tally].filter(([k]) => !k.startsWith('JUDGE') && k !== 'UNMAPPED').sort((a, b) => b[1].n - a[1].n)) {
    console.log(`    ${String(t.n).padStart(5)}  ${k}`);
    for (const [p, n] of [...t.pairs].sort((a, b) => b[1] - a[1]).slice(0, 8)) {
      console.log(`             ${String(n).padStart(5)}  ${p}`);
    }
  }

  console.log(`\n  JUDGEMENT — ${judgeN} edges (${((judgeN / E.length) * 100).toFixed(0)}%)`);
  for (const [k, t] of grab('JUDGE').sort((a, b) => b[1].n - a[1].n)) {
    const q = k.slice(6);
    console.log(`    ${String(t.n).padStart(5)}  ${q.padEnd(22)} -> ${JUDGEMENTS[q]?.decide ?? '?'}`);
  }

  if (unmappedN) {
    console.log(`\n  UNMAPPED (${unmappedN}) — schema is INCOMPLETE. Each of these has no rule:`);
    for (const [p, n] of [...tally.get('UNMAPPED').pairs].sort((a, b) => b[1] - a[1])) console.log(`    ${String(n).padStart(5)}  ${p}`);
  }
  if (assertN) {
    console.log(`\n  ASSERT-FAIL (${assertN}) — a narrow_kinds violation:`);
    for (const [p, n] of [...tally.get('ASSERT-FAIL').pairs].sort((a, b) => b[1] - a[1])) console.log(`    ${String(n).padStart(5)}  ${p}`);
  }
  console.log(`\n  totals: mechanical ${sum([...tally].filter(([k]) => !k.startsWith('JUDGE') && k !== 'UNMAPPED'))}`
    + `  judgement ${judgeN}  unmapped ${unmappedN}  assert-fail ${assertN}`);
  if (unmappedN || assertN) console.log(`\n  NOT READY TO FAN OUT. Fix the schema until UNMAPPED is zero.\n`);
  else console.log(``);
}

function cmdProcedure() {
  const L = [];
  let n = 0;
  L.push(`# Edge decision procedure — GENERATED. Do not hand-edit.`);
  L.push(``);
  L.push(`Generated from \`data/_relation_schema.json\` by \`node scripts/relate.mjs procedure\`.`);
  L.push(`Regenerate it rather than correcting it. Build: ${meta.generated}`);
  L.push(``);
  L.push(`## Order of tests — follow in this order, first match wins.`);
  L.push(``);
  L.push(`| # | condition | result |`);
  L.push(`| --- | --- | --- |`);
  const step = (cond, res) => L.push(`| ${++n} | ${cond} | ${String(res).replace(/\|/g, '\\|')} |`);
  step('the source node is a `note`', '**STOP — report it.** A note has no supply edges.');
  step('the edge is listed in `data/_relation_fixes.json`', 'apply that entry verbatim: `delete`, `reassign` or `reverse`');
  step('the target is a `note`', '`about`');
  for (const [q, j] of Object.entries(JUDGEMENTS)) {
    step(`kind pair is \`${q.replace('>', ' → ')}\``, `**JUDGE** — ${j.decide}`);
  }
  for (const [name, r] of Object.entries(RELATIONS)) {
    if (r.derived_from || !r.stored?.length) continue;
    const pairs = r.stored.filter((p) => !p.startsWith('*')).join(', ') || 'anything';
    step(`kind pair is one of: ${pairs}`, `\`${name}\``);
  }
  L.push(`| ${++n} | **nothing above matched** | **STOP — report it. The schema is missing a case; do not invent a relation.** |`);
  L.push(``);

  L.push(`## The judgement questions`);
  L.push(``);
  L.push(`These are the only places a human decision is required. Everything else is a`);
  L.push(`table lookup. Counts are current against the build above.`);
  L.push(``);
  let qn = 0;
  for (const [q, j] of Object.entries(JUDGEMENTS)) {
    const counts = ALL.filter((e) => e.pair === q).length;
    L.push(`### ${++qn}. \`${q.replace('>', ' → ')}\` — ${counts} edges`);
    L.push(``);
    L.push(`**Decide:** ${j.decide}`);
    L.push(``);
    L.push(`> ${j.test}`);
    L.push(``);
    if (q === 'material>material') {
      L.push(`Worked examples: RELATIONS.md §3.1 — ten borderline cases drawn from the tree — plus`);
      L.push(`the \`examples\` arrays in the schema under \`relations["made of"]\` and`);
      L.push(`\`relations["made from"]\`. **Read them before you start.** This is the pair the`);
      L.push(`calibration gate measures, and the one most likely to be decided wrong.`);
      L.push(``);
    }
    if (j.provenance_shortcut) { L.push(`**Provenance.** ${j.provenance_shortcut}`); L.push(``); }
    if (j.note) { L.push(`**Note.** ${j.note}`); L.push(``); }
  }

  L.push(`## What is forbidden`);
  L.push(``);
  L.push(`- \`consumes\` never targets a \`part\`. ${SCHEMA.narrow_kinds.consumes_part}`);
  L.push(`- \`made by\` is DERIVED from \`produces\` and is never stored. ${RELATIONS['made by'].note}`);
  L.push(`- a \`note\` participates only in \`about\`, in either direction.`);
  L.push(`- no relation means "a group of related nodes". If you need one, it is a query, not an edge.`);
  L.push(`- do not invent a kind. If a node is filed under the wrong kind, report it — \`kind\` changes`);
  L.push(`  are central, not per-fragment (RELATIONS.md §6).`);
  L.push(``);
  console.log(L.join('\n'));
}

function edgesFor(file) {
  return ALL.filter((e) => N[e.parent]?.file === file || N[e.child]?.file === file);
}

function cmdWork() {
  const file = flag('file');
  if (!file || file === true) { console.error('need --file 20-board.json'); process.exit(1); }
  const only = flag('only', 'judge');
  const INDEX_PARENTS = new Set(SCHEMA.judgement_questions._index_parents ?? []);
  /* Edges whose PARENT is an index or grouping node are centrally handled in
   * wave 4, not by agents. Round 3 calibration found two such rows in a 27-row
   * sample -- c64.packaging and c64.mains -- so the 300-edge part->process set
   * contains an unmeasured number of them. */
  const want = (disp) => (only === 'all' ? true
    : only === 'judge' ? (disp === 'JUDGE' || disp === 'NO-HOME' || disp === 'REVIEW')
      : disp === only.toUpperCase());
  const all = edgesFor(file);
  let mine = all.filter((e) => want(e.disposition));
  const skipped = all.length - mine.length;
  const idxOut = mine.filter((e) => INDEX_PARENTS.has(e.parent)).length;
  mine = mine.filter((e) => !INDEX_PARENTS.has(e.parent));
  const byKind = new Map();
  for (const r of mine) {
    const k = r.disposition === 'JUDGE' ? `JUDGE ${r.q}` : r.disposition;
    if (!byKind.has(k)) byKind.set(k, []);
    byKind.get(k).push(r);
  }
  console.log(`# work list — ${file}`);
  console.log(`# generated ${meta.generated} by scripts/relate.mjs. Do not hand-edit.`);
  console.log(`# ${all.length} edges touch this fragment; ${mine.length} need a decision`
    + (skipped ? `; ${skipped} are mechanical and applied by script, not by you.` : '.')
    + (idxOut ? `\n# ${idxOut} more have an INDEX/GROUPING parent and are centrally handled in wave 4 -- excluded, report only.` : ''));
  console.log(`# 'out' = this fragment owns the edge (stored on the parent). 'in' = the other end does.\n`);
  for (const [k, list] of [...byKind].sort((a, b) => b[1].length - a[1].length)) {
    console.log(`## ${k} — ${list.length}`);
    if (k.startsWith('JUDGE')) {
      const q = k.slice(6);
      console.log(`\nquestion: ${JUDGEMENTS[q].decide}`);
      console.log(`test:     ${JUDGEMENTS[q].test}`);
      if (JUDGEMENTS[q].note) console.log(`note:     ${JUDGEMENTS[q].note}`);
      console.log(``);
    }
    for (const r of list) {
      const own = N[r.parent]?.file === file ? 'out' : 'in ';
      console.log(`${own} ${r.pair}\t${r.parent}\t${nameOf(r.parent)}\t${r.child}\t${nameOf(r.child)}\t[was ${r.was}]${r.to ? `\t=> ${r.to}` : ''}`);
    }
    console.log(``);
  }
}

function cmdGold() {
  const n = Number(flag('n', 80));
  const out = [];
  for (const q of Object.keys(JUDGEMENTS)) {
    const pool = E.filter((e) => e.pair === q && K(e.parent) !== 'note' && !DELETE_SET.has(`${e.parent}>${e.child}`));
    const quota = Math.max(2, Math.round((n * pool.length) / E.length));
    const stride = Math.max(1, Math.floor(pool.length / quota));
    let taken = 0;
    for (let i = 0; i < pool.length && taken < quota; i += stride, taken++) out.push(pool[i]);
  }
  console.log(`# calibration gold set — ${out.length} edges`);
  console.log(`# generated ${meta.generated} by scripts/relate.mjs gold`);
  console.log(`# Two agents label these BLIND and independently. Show neither the other's labels,`);
  console.log(`# and show neither a reference answer. Compare the two label sets against each other.`);
  console.log(`# made-of-vs-made-from below 85% agreement means the TEST is wrong, not the agents.\n`);
  for (const e of out) {
    const j = JUDGEMENTS[e.pair];
    console.log(`${e.pair}\t${j.decide}\t${e.parent}\t${nameOf(e.parent)}\t${e.child}\t${nameOf(e.child)}`);
  }
  console.log(``);
}

function cmdVerifyInputs() {
  const rows = ALL.filter((e) => e.pair === 'process->material' && e.was === 'from');
  const flags = [];
  for (const r of rows) {
    const cn = nameOf(r.child);
    if (K(r.child) !== 'material') flags.push({ ...r, why: `target is a ${K(r.child)}, not a material` });
    else if (cn.includes(':')) flags.push({ ...r, why: 'target name looks like a product index, not a substance' });
  }
  console.log(`\n  inputs-derived process->material edges: ${rows.length}`);
  console.log(`  auto-flagged:                          ${flags.length}`);
  console.log(`  clean enough to auto-assign:           ${rows.length - flags.length}\n`);
  for (const f of flags) console.log(`  FLAG\t${f.parent}\t${f.child}\t${f.why}\t${nameOf(f.child)}`);
  console.log(`\n  DECIDED 2026-10-04: none of these are trusted. All ${rows.length} get an agent verdict.`);
  console.log(`  Split them with: node scripts/relate.mjs work --file <fragment> --only JUDGE\n`);
}

function cmdAudit() {
  const fails = [], warns = [];
  const seen = new Map();
  for (const e of ALL) {
    if (e.disposition === 'UNMAPPED') {
      const k = `${e.disposition}|${e.pair}|${e.why}`;
      if (!seen.has(k)) { seen.set(k, []); fails.push(`UNMAPPED kind pair ${e.pair} — ${e.why}  (e.g. ${e.parent} -> ${e.child})`); }
      seen.get(k).push(e);
    } else if (e.disposition === 'ASSERT-FAIL') {
      const k = `A|${e.disposition}|${e.pair}`;
      if (!seen.has(k)) { seen.set(k, []); fails.push(`ASSERT-FAIL ${e.pair} — ${e.why}  (e.g. ${e.parent} -> ${e.child})`); }
      seen.get(k).push(e);
    }
  }
  /* The note-dissolution backlog is reported with its count rather than as a bare
   * FAIL, because 17 notes with outgoing edges is a KNOWN, SCHEDULED piece of
   * work (RELATIONS.md section 9, wave 4.2) and not a surprise. Phase 0: was 21;
   * the build.mjs kind:note from-guard closed 4 from-leaks, leaving 15 children-
   * holders + 2 dual-relation notes. Still fails so it cannot be forgotten. */
  const NOTE_BACKLOG_KNOWN = 17;
  let noteOut = 0;
  for (const id of ids) {
    if (K(id) !== 'note') continue;
    if ((N[id].children?.length ?? 0) || (N[id].from?.length ?? 0)) noteOut++;
  }
  if (noteOut) {
    fails.push(`${noteOut} note nodes have outgoing edges; only \`about\` is legal`
      + `   [KNOWN BACKLOG: ${NOTE_BACKLOG_KNOWN} expected, wave 4.2 dissolves them; delta ${noteOut - NOTE_BACKLOG_KNOWN}]`);
  }
  const UTIL = Object.keys(HUB_RULES);
  const utilLeft = UTIL.filter((u) => N[u] && K(u) === 'facility');
  if (utilLeft.length) warns.push(`${utilLeft.length} utility deliveries still typed facility: ${utilLeft.join(', ')}`);
  else warns.push(`OK: all ${UTIL.length} utility deliveries retyped to material`);

  // connectivity: directed walk, refinement down and flow both ways (RELATIONS.md section 8)
  const CARRIES = new Set(SCHEMA.connectivity.carries);
  const DROPS = new Set(['c64.bottoms-out', 'c64.extras', 'unlinked.catalogue']);
  const seenNodes = new Set(['c64']); const walkStack = ['c64'];
  while (walkStack.length) {
    const x = walkStack.pop();
    for (const c of N[x].children ?? []) if (N[c] && !DROPS.has(c) && !seenNodes.has(c)) { seenNodes.add(c); walkStack.push(c); }
    if (K(x) === 'note') continue;
    for (const f of N[x].from ?? []) if (N[f] && !seenNodes.has(f)) { seenNodes.add(f); walkStack.push(f); }
  }
  const orphans = ids.filter((i) => !seenNodes.has(i));
  if (orphans.length) warns.push(`${orphans.length} nodes unreachable from the root with the three index containers dropped (wave 4.3 reconnects them)`);

  console.log(`\n  build: ${meta.generated}`);
  console.log(`  ${fails.length} FAIL  ${warns.length} WARN\n`);
  for (const f of fails.slice(0, 40)) console.log(`    x ${f}`);
  if (fails.length > 40) console.log(`    ... and ${fails.length - 40} more`);
  for (const w of warns) console.log(`    ! ${w}`);
  console.log(``);
  process.exit(fails.length ? 2 : 0);
}

async function cmdEmitFixes() {
  const del = [], rev = {};

  /* Edges a pattern cannot decide, decided by reading the prose. Kept here
   * rather than in a regex so the reason survives with the decision. */
  const HAND = new Map(Object.entries({
    'metal.copper>metal.copper.wire': { action: 'delete', why: 'HAND 2026-10-04: metal.copper is a PRODUCT INDEX ("Copper: track, winding wire, foil, contacts"), so `made of metal.copper -> metal.copper.wire` is circular. This edge was briefly the worked example for "same substance, different shape" in RELATIONS.md 3.1, which contradicted 7.3 of the same document; calibration agent B caught it. The index reading wins, because reading "made of the copper index" as "made of copper" is exactly the conflation 7.3 describes.' },
    'metal.copper.cathode>metal.copper.wire': { action: 'reassign', to_relation: 'made of', why: 'HAND: the cathode is 99.99% copper and the wire is copper. Skips the drawing stage, which is a `step`, not a `made from`' },
    'metal.solder>metal.solder.wire': { action: 'reassign', to_relation: 'made of', why: 'HAND: worked example in RELATIONS.md 3.1. A solder-wire spec sheet reads Sn63/Pb37 core, rosin core' },
    'chem.abs>chem.abs.c64-case': { action: 'reassign', to_relation: 'made of', why: 'HAND: the C64 case IS ABS. Spec sheet: acrylonitrile-butadiene-styrene, black' },
    'chem.abs>chem.abs.knob': { action: 'reassign', to_relation: 'made of', why: 'HAND: the fire button is injection-moulded ABS' },
    'c64.joystick.knob.abs>c64.joystick.knob.abs.fire-button': { action: 'reassign', to_relation: 'made of', why: 'HAND: the fire button and the third knob button are moulded from this ABS. Spec sheet: acrylonitrile-butadiene-styrene, black' },
    'facility.compressed-air.scrubber-packing>chem.propylene.polymerisation': { action: 'delete', why: 'HAND: the packing media is already a child node ("PVC / PP packing media"). The target is also a kind bug -- `Polypropylene` is typed process and is a substance' },
    'facility.electricity>facility.electricity.distribution-busbar': { action: 'delete', why: 'HAND 2026-10-04, found by calibration agent A: electricity is not MADE OF busbar trunking, it is DELIVERED THROUGH it. The relation set has no "delivered through", and forcing one would be exactly the conflation this migration exists to remove. The busbar already appears on the utility node as an `at` edge, which is where delivery infrastructure belongs.' },
  }));

  // ---- material -> part (18). None reverse. Three outcomes: delete (wrong or
  // duplicated), reassign to `made of` (legitimate, just not a reversal), or
  // REVIEW (needs a human). Patterns here are a WORK LIST; anything that does
  // not clearly match falls through to REVIEW on purpose.
  for (const e of ALL.filter((x) => x.pair === 'material>part')) {
    const key = `${e.parent}>${e.child}`;
    const cn = nameOf(e.child), pn = nameOf(e.parent);
    if (HAND.has(key)) { del.push({ from: e.parent, to: e.child, was: e.was, ...HAND.get(key), parentName: pn, childName: cn }); continue; }
    const hasReverse = (N[e.child]?.from ?? []).includes(e.parent) || (N[e.child]?.children ?? []).includes(e.parent);
    let why, action, to;
    if (hasReverse) { action = 'delete'; why = 'the opposite edge is already stored'; }
    else if (/quartz.*crystal/i.test(cn)) { action = 'delete'; why = 'silicon and quartz are unrelated materials; this edge is textual adjacency, not a material flow'; }
    else if (/acetylene cylinder/i.test(cn)) { action = 'delete'; why = 'a gas cylinder is steel, not made from oxygen'; }
    else if (/blister copper anode/i.test(cn)) { action = 'delete'; why = 'duplicates cathode -> anode one level up'; }
    else if (/magnet wire/i.test(cn) && e.parent !== 'metal.copper' && /wire|film|cable|ribbon|alloy/i.test(pn)) { action = 'delete'; why = 'name-index accident: a finished wire or film is not made from another finished wire'; }
    else { action = 'REVIEW'; why = 'material -> part with no reverse edge and no clear pattern; read the prose'; }
    del.push({ from: e.parent, to: e.child, was: e.was, action, to_relation: to, why, parentName: pn, childName: cn });
  }

  // ---- tool -> process (20)
  for (const e of ALL.filter((x) => x.pair === 'tool>process')) {
    const key = `${e.parent}>${e.child}`;
    const hasReverse = (N[e.child]?.children ?? []).includes(e.parent) || (N[e.child]?.from ?? []).includes(e.parent);
    const cn = nameOf(e.child), tn = nameOf(e.parent);
    if (HAND.has(key)) { const h = HAND.get(key); if (h.action === 'reverse') rev[key] = h.to_relation; del.push({ from: e.parent, to: e.child, was: e.was, ...h, parentName: tn, childName: cn }); continue; }
    if (hasReverse) { del.push({ from: e.parent, to: e.child, was: e.was, action: 'delete', why: 'the opposite edge is already stored', parentName: tn, childName: cn }); continue; }
    if (/diamond/i.test(cn)) { del.push({ from: e.parent, to: e.child, was: e.was, action: 'reassign', to_relation: 'contains', why: 'the tool is impregnated WITH industrial diamond; it does not use the process that makes it', parentName: tn, childName: cn }); continue; }
    rev[key] = 'uses';
    del.push({ from: e.parent, to: e.child, was: e.was, action: 'reverse', to_relation: 'uses', why: 'the operation happens inside the machine', parentName: tn, childName: cn });
  }

  const out = {
    $comment: 'Per-edge dispositions decided by measurement, then reviewed by hand. Generated by `node scripts/relate.mjs emit-fixes --write`. Anything in `review` is NOT decided and must not be applied.',
    $source: `built from public/tree.json generated ${meta.generated}`,
    delete: del.filter((d) => d.action === 'delete'),
    reassign: del.filter((d) => d.action === 'reassign'),
    reverse: rev,
    review: del.filter((d) => d.action === 'REVIEW'),
  };
  console.log(`\n  delete ${out.delete.length}  reverse ${Object.keys(rev).length}  reassign ${out.reassign.length}  REVIEW ${out.review.length}`);
  for (const [label, list] of [['DELETE', out.delete], ['REASSIGN', out.reassign]]) {
    console.log(`\n## ${label} (${list.length})`);
    for (const d of list) console.log(`  ${d.from} -> ${d.to}${d.to_relation ? `  [${d.to_relation}]` : ''}\n      ${d.why}`);
  }
  console.log(`\n## REVERSE -> uses (${Object.keys(rev).length})`);
  for (const k of Object.keys(rev)) console.log(`  ${k.replace('>', ' -> ')}`);
  console.log(`\n## REVIEW — NOT DECIDED (${out.review.length})`);
  for (const d of out.review) console.log(`  ${d.parentName}  ->  ${d.childName}`);
  console.log(``);

  if (flag('write') === true) {
    await writeFile(path.join(ROOT, 'data/_relation_fixes.json'), JSON.stringify(out, null, 2));
    console.log(`  WROTE data/_relation_fixes.json\n`);
  } else {
    console.log(`  dry run. re-run with --write to save.\n`);
  }
}

const COMMANDS = {
  plan: cmdPlan, procedure: cmdProcedure, work: cmdWork, gold: cmdGold,
  'verify-inputs': cmdVerifyInputs, audit: cmdAudit, 'emit-fixes': cmdEmitFixes,
};
const fn = COMMANDS[cmd];
if (!fn) { console.error(`unknown command: ${cmd}\n  ${Object.keys(COMMANDS).join(' | ')}`); process.exit(1); }
fn();
